-- Catálogo de permissões alinhado ao menu — GERADO por
-- frontend/scripts/gerar-catalogo-permissoes.mjs a partir de lib/permissions/menu.ts.
-- Não edite à mão: mude o menu e gere de novo.
--
-- Idempotente. Não muda o acesso de ninguém: só cadastra códigos novos e acerta
-- nome, grupo, rota e ordem. Um código NOVO nasce sem estar em grupo nenhum —
-- depois de aplicar, marque-o no modelo dos grupos que devem ter a tela
-- (/admin/permissoes → Por grupo).

-- 1. Códigos novos (os que já existem ficam como estão).
INSERT INTO public.permissoes (codigo, nome, grupo, rota, ordem)
SELECT v.codigo, v.nome, v.grupo, v.rota, v.ordem
FROM (VALUES
  ('dashboard', 'Dashboard', 'Geral', '/', 10),
  ('atendimentos', 'Atendimentos', 'Pacientes', '/solicitar', 20),
  ('gestao', 'Gestão Recepção', 'Pacientes', '/central-pacientes', 30),
  ('autorizacoes_avulsas', 'Autorizações Avulsas', 'Pacientes', '/autorizacoes-avulsas', 40),
  ('acompanhamento_laudos', 'Status Laudos e Senhas', 'Pacientes', '/acompanhamento/laudos', 50),
  ('status_contratos', 'Status Contratos', 'Pacientes', '/acompanhamento/contratos', 60),
  ('outros_convenios', 'Outros Convênios', 'Pacientes', '/outros-convenios', 70),
  ('escala_terapeutica', 'Gestão', 'Terapêutico', '/central-terapeutas', 80),
  ('analise_tratativas', 'Análise de Evolução', 'Terapêutico', '/analise-tratativas', 90),
  ('terapeutico_auditoria_evolucoes', 'Auditoria de Evoluções', 'Terapêutico', '/terapeutico/auditoria-evolucoes', 100),
  ('terapeutico_pdi', 'PDI - Controle', 'Terapêutico', '/terapeutico/prazos-pdi', 110),
  ('terapeutico_pdi_painel', 'PDI - Painel', 'Terapêutico', '/terapeutico/pdi-painel-analista', 120),
  ('cco', 'Conciliação ASSIM', 'Autorização', '/cco', 130),
  ('auditoria_assim', 'Conferência ASSIM', 'Autorização', '/auditoria-assim?tab=auditoria', 140),
  ('reconciliacao_assim', 'Reconciliação ASSIM', 'Autorização', '/auditoria-assim?tab=reconciliacao', 150),
  ('conferencia_guias', 'Conferência de Guias', 'Autorização', '/conferencia-guias', 160),
  ('insumos', 'Solicitações', 'Suprimentos', '/insumos', 170),
  ('cronograma_grade', 'Grade', 'Cronograma', '/cronograma/grade', 180),
  ('cronograma_saida_profissional', 'Saída Profissional', 'Cronograma', '/cronograma/saida-profissional', 190),
  ('cronograma_ocupacao_paciente', 'Ocupação Paciente', 'Cronograma', '/cronograma/ocupacao-paciente', 200),
  ('reposicao_faltas', 'Reposição de Faltas', 'Cronograma', '/cronograma/reposicao', 210),
  ('ocupacao_clinica', 'Oportunidades recusadas', 'Cronograma', '/cronograma/ocupacao?tab=oportunidades-recusadas', 220),
  ('ocupacao_clinica_gaps', 'Diferença: Laudo e Oferta', 'Cronograma', '/cronograma/ocupacao?tab=gaps', 230),
  ('ocupacao_clinica_inconsistencias', 'Inconsistências e Exceções', 'Cronograma', '/cronograma/ocupacao?tab=inconsistencias', 240),
  ('ocupacao_profissionais', 'Ocupação de Profissionais', 'Indicadores', '/cronograma/indicadores?tab=profissionais', 250),
  ('indicadores_ocupacao_unidades', 'Ocupação Clínica', 'Indicadores', '/cronograma/indicadores?tab=unidades', 260),
  ('indicadores_pacientes', 'Dashboard de Pacientes', 'Indicadores', '/cronograma/indicadores?tab=pacientes', 270),
  ('indicadores_previsao_receitas', 'Previsão de Receitas', 'Indicadores', '/cronograma/indicadores?tab=previsao-receitas', 280),
  ('indicadores_alimentar_bd', 'Preencher Receitas Faturadas', 'Indicadores', '/cronograma/indicadores?tab=alimentar-bd', 290),
  ('indicadores_comparativo_sessoes', 'Comparativo de Sessões', 'Indicadores', '/cronograma/indicadores?tab=comparativo-sessoes', 300),
  ('cadastros_pacientes', 'Pacientes', 'Cadastros', '/cadastros/pacientes', 310),
  ('cadastros_profissionais', 'Profissionais', 'Cadastros', '/cadastros/profissionais', 320),
  ('cadastros_terapias', 'Terapias', 'Cadastros', '/cadastros/terapias', 330),
  ('cadastros_convenios', 'Convênios', 'Cadastros', '/cadastros/convenios', 340),
  ('cronograma_valores_convenio', 'Cadastro de Valores', 'Cadastros', '/cadastros/cadastro-valores', 350),
  ('cadastros_feriados', 'Feriados', 'Cadastros', '/cadastros/feriados', 360),
  ('cadastros_taxas', 'Variáveis & Taxas', 'Cadastros', '/cadastros/taxas-e-parametros', 370),
  ('cadastros_contratos', 'Contratos', 'Cadastros', '/cadastros/contratos', 380),
  ('cronograma_ocupacao_salas', 'Ocupação de Salas', 'Relacionamento Prestador', '/relacionamento-prestador/ocupacao-salas', 390),
  ('cronograma_solicitacoes', 'Simulação de Novo Prestador', 'Relacionamento Prestador', '/relacionamento-prestador/solicitacoes', 400),
  ('cronograma_disponibilidade_interna', 'Ocupar Profissionais Disponíveis', 'Relacionamento Prestador', '/relacionamento-prestador/ocupar-profissionais-disponiveis', 410),
  ('relacionamento_prestador_analise', 'Rem. Mês - Previsão', 'Relacionamento Prestador', '/relacionamento-prestador/analise', 420),
  ('relacionamento_prestador_rp', 'Remuneração Total', 'Relacionamento Prestador', '/relacionamento-prestador/rp', 430),
  ('relacionamento_prestador_individual', 'Remuneração Individual', 'Relacionamento Prestador', '/relacionamento-prestador/individual', 440),
  ('relacionamento_prestador_pep', 'Entregas PEP', 'Relacionamento Prestador', '/relacionamento-prestador/pep', 450),
  ('relacionamento_prestador_pep_historico', 'PEP - Histórico', 'Relacionamento Prestador', '/relacionamento-prestador/pep-historico', 460),
  ('tv_avisos', 'TV da Recepção', 'Marketing', '/tv-avisos', 470),
  ('usuarios', 'Usuários', 'Administração', '/admin', 480),
  ('permissoes', 'Permissões', 'Administração', '/admin/permissoes', 490),
  ('api_integracao', 'API', 'Administração', '/admin/api', 500),
  ('robo_sharepoint', 'Robô SharePoint', 'Administração', '/admin/robo-sharepoint', 510),
  ('connect', 'Pulsar Connect', 'Geral', '/connect', 520)
) AS v(codigo, nome, grupo, rota, ordem)
ON CONFLICT (codigo) DO NOTHING;

-- 2. Nome, grupo, rota e ordem iguais ao menu.
UPDATE public.permissoes p
SET nome = v.nome, grupo = v.grupo, rota = v.rota, ordem = v.ordem
FROM (VALUES
  ('dashboard', 'Dashboard', 'Geral', '/', 10),
  ('atendimentos', 'Atendimentos', 'Pacientes', '/solicitar', 20),
  ('gestao', 'Gestão Recepção', 'Pacientes', '/central-pacientes', 30),
  ('autorizacoes_avulsas', 'Autorizações Avulsas', 'Pacientes', '/autorizacoes-avulsas', 40),
  ('acompanhamento_laudos', 'Status Laudos e Senhas', 'Pacientes', '/acompanhamento/laudos', 50),
  ('status_contratos', 'Status Contratos', 'Pacientes', '/acompanhamento/contratos', 60),
  ('outros_convenios', 'Outros Convênios', 'Pacientes', '/outros-convenios', 70),
  ('escala_terapeutica', 'Gestão', 'Terapêutico', '/central-terapeutas', 80),
  ('analise_tratativas', 'Análise de Evolução', 'Terapêutico', '/analise-tratativas', 90),
  ('terapeutico_auditoria_evolucoes', 'Auditoria de Evoluções', 'Terapêutico', '/terapeutico/auditoria-evolucoes', 100),
  ('terapeutico_pdi', 'PDI - Controle', 'Terapêutico', '/terapeutico/prazos-pdi', 110),
  ('terapeutico_pdi_painel', 'PDI - Painel', 'Terapêutico', '/terapeutico/pdi-painel-analista', 120),
  ('cco', 'Conciliação ASSIM', 'Autorização', '/cco', 130),
  ('auditoria_assim', 'Conferência ASSIM', 'Autorização', '/auditoria-assim?tab=auditoria', 140),
  ('reconciliacao_assim', 'Reconciliação ASSIM', 'Autorização', '/auditoria-assim?tab=reconciliacao', 150),
  ('conferencia_guias', 'Conferência de Guias', 'Autorização', '/conferencia-guias', 160),
  ('insumos', 'Solicitações', 'Suprimentos', '/insumos', 170),
  ('cronograma_grade', 'Grade', 'Cronograma', '/cronograma/grade', 180),
  ('cronograma_saida_profissional', 'Saída Profissional', 'Cronograma', '/cronograma/saida-profissional', 190),
  ('cronograma_ocupacao_paciente', 'Ocupação Paciente', 'Cronograma', '/cronograma/ocupacao-paciente', 200),
  ('reposicao_faltas', 'Reposição de Faltas', 'Cronograma', '/cronograma/reposicao', 210),
  ('ocupacao_clinica', 'Oportunidades recusadas', 'Cronograma', '/cronograma/ocupacao?tab=oportunidades-recusadas', 220),
  ('ocupacao_clinica_gaps', 'Diferença: Laudo e Oferta', 'Cronograma', '/cronograma/ocupacao?tab=gaps', 230),
  ('ocupacao_clinica_inconsistencias', 'Inconsistências e Exceções', 'Cronograma', '/cronograma/ocupacao?tab=inconsistencias', 240),
  ('ocupacao_profissionais', 'Ocupação de Profissionais', 'Indicadores', '/cronograma/indicadores?tab=profissionais', 250),
  ('indicadores_ocupacao_unidades', 'Ocupação Clínica', 'Indicadores', '/cronograma/indicadores?tab=unidades', 260),
  ('indicadores_pacientes', 'Dashboard de Pacientes', 'Indicadores', '/cronograma/indicadores?tab=pacientes', 270),
  ('indicadores_previsao_receitas', 'Previsão de Receitas', 'Indicadores', '/cronograma/indicadores?tab=previsao-receitas', 280),
  ('indicadores_alimentar_bd', 'Preencher Receitas Faturadas', 'Indicadores', '/cronograma/indicadores?tab=alimentar-bd', 290),
  ('indicadores_comparativo_sessoes', 'Comparativo de Sessões', 'Indicadores', '/cronograma/indicadores?tab=comparativo-sessoes', 300),
  ('cadastros_pacientes', 'Pacientes', 'Cadastros', '/cadastros/pacientes', 310),
  ('cadastros_profissionais', 'Profissionais', 'Cadastros', '/cadastros/profissionais', 320),
  ('cadastros_terapias', 'Terapias', 'Cadastros', '/cadastros/terapias', 330),
  ('cadastros_convenios', 'Convênios', 'Cadastros', '/cadastros/convenios', 340),
  ('cronograma_valores_convenio', 'Cadastro de Valores', 'Cadastros', '/cadastros/cadastro-valores', 350),
  ('cadastros_feriados', 'Feriados', 'Cadastros', '/cadastros/feriados', 360),
  ('cadastros_taxas', 'Variáveis & Taxas', 'Cadastros', '/cadastros/taxas-e-parametros', 370),
  ('cadastros_contratos', 'Contratos', 'Cadastros', '/cadastros/contratos', 380),
  ('cronograma_ocupacao_salas', 'Ocupação de Salas', 'Relacionamento Prestador', '/relacionamento-prestador/ocupacao-salas', 390),
  ('cronograma_solicitacoes', 'Simulação de Novo Prestador', 'Relacionamento Prestador', '/relacionamento-prestador/solicitacoes', 400),
  ('cronograma_disponibilidade_interna', 'Ocupar Profissionais Disponíveis', 'Relacionamento Prestador', '/relacionamento-prestador/ocupar-profissionais-disponiveis', 410),
  ('relacionamento_prestador_analise', 'Rem. Mês - Previsão', 'Relacionamento Prestador', '/relacionamento-prestador/analise', 420),
  ('relacionamento_prestador_rp', 'Remuneração Total', 'Relacionamento Prestador', '/relacionamento-prestador/rp', 430),
  ('relacionamento_prestador_individual', 'Remuneração Individual', 'Relacionamento Prestador', '/relacionamento-prestador/individual', 440),
  ('relacionamento_prestador_pep', 'Entregas PEP', 'Relacionamento Prestador', '/relacionamento-prestador/pep', 450),
  ('relacionamento_prestador_pep_historico', 'PEP - Histórico', 'Relacionamento Prestador', '/relacionamento-prestador/pep-historico', 460),
  ('tv_avisos', 'TV da Recepção', 'Marketing', '/tv-avisos', 470),
  ('usuarios', 'Usuários', 'Administração', '/admin', 480),
  ('permissoes', 'Permissões', 'Administração', '/admin/permissoes', 490),
  ('api_integracao', 'API', 'Administração', '/admin/api', 500),
  ('robo_sharepoint', 'Robô SharePoint', 'Administração', '/admin/robo-sharepoint', 510),
  ('connect', 'Pulsar Connect', 'Geral', '/connect', 520)
) AS v(codigo, nome, grupo, rota, ordem)
WHERE p.codigo = v.codigo;
